connections:
- name: vagrant_password
  adapter: "#ssh"
  settings:
    host: 192.168.42.42
    port: 22
    user: vagrant
    password: vagrant
- name: vagrant_key
  adapter: "#ssh"
  settings:
    host: 192.168.42.42
    port: 22
    user: vagrant
    password: vagrant
    keyPath: '/home/.ssh/id_rsa'

projects:
- name: Vagrant
  settings:
    connection: "vagrant_password"
    connectionPoolCapacity: 5
    connectionPoolInitCapacity: 1
  search:
    settings:
      maxSearchIntervalSeconds: 3600
    logFile:
      name:
        template: "/(date).log/"
        timezone: "#server | #format | Asia/Novosibirsk"
        dateFormat: YmDHiS
      record:
        template: "^(?P<date>[A-Za-z]{3} \\d{2} \\d{2}:\\d{2}:\\d{2}) (?:(?P<user>.+?) )(?:(?P<command>.+?):) (?P<message>.*)"
        timezone: "#server | #format | Asia/Novosibirsk"
        dateFormat: YmDHiS
    fields:
    - name: date
      type: "#range(date)"
      format: Y-m-d H:i:s
      isRequired: true
    - name: user
      type: "#string"
    - name: command
      type: "#string"
    - name: message
      type: "#string"
  environments:
  - name: live
    pathToLogs: "/var/www/apache/"

